=== Adrian-Gordon/nodebets/public/resources/api/conf/1.0/docs/schemas/raceschema.json
{	
	"$schema":"http://json-schema.org/draft-04/schema#",
	"id":"http://dimplecds.com/raceschema.json",
	"type":"object",
	"properties":{
		"_id":{"type":"string", "minLength": 6, "maxLength": 6},
		"conditions":{"type":"array",
					  "items":{
					  	"oneOf":[{
						  		"type":"object",
							  	"properties":{
							  		"conditiontype":{
							  			"type":"string",
							  			"enum":["distance"]
							  		},
							  		"miles":{
							  			"type":"number"
							  		},
							  		"furlongs":{
							  			"type":"number"
							  		},
							  		"yards":{
							  			"type":"number"
							  		}
							  	}
					  			},
					  			{
						  		"type":"object",
							  	"properties":{
							  		"conditiontype":{
							  			"type":"string",
							  			"enum":["conditions"]
							  		},
							  		"ageconditions":{
							  			"type":"object",
							  			"properties":{
							  				"lower":{
							  					"type":"number"
							  				},
							  				"upper":{
							  					"type":"number"
							  				}
							  			}
							  		}
							  	}
					  			},
					  			{
						  		"type":"object",
							  	"properties":{
							  		"conditiontype":{
							  			"type":"string",
							  			"enum":["going"]
							  		},
							  		"going":{
							  			"type":"string",
							  			"enum":["Fast","Good"]
							  		}
							  	}
					  			}
						  	
						]
					  }
					},
		"date":{
			"type":"string",
			"format":"date-time"
		},
		"distance":{
			"type":"number"
		},
		"going":{
			"type":"string",
			"enum":["Fast","Good"]
		},
		"iscomplete":{
			"type":"boolean"
		},
		"meeting":{
			"type":"string",
			"pattern":"^[A-Z\\s]+$"
		},
		"offtime":{
			"type":"string"
		},
		"racetype":{
			"type":"string",
			"enum":["FLAT","HURDLE","CHASE"]
		},
		"runners":{
			"type":"array",
			"items":{
				"type":"string",
				"minLength": 6, 
				"maxLength": 6

			}
		},
		"surface":{
			"type":"string",
			"enum":["AW", "TURF"]
		},
		"winningtime":{
			"type":"number"
		}
	}
}

=== Adrian-Gordon/nodebets/public/resources/api/conf/1.0/docs/examples/get-race-example-1.json
{"_id":"663916",
 "conditions":[{"conditiontype":"conditions",
 				"ageconditions":{"lower":3}},
 				{"conditiontype":"distance","miles":1,"furlongs":1,"yards":0},
 				{"conditiontype":"going","going":"Fast"}],
 "date":"2016-11-25T00:00:00.000Z",
 "distance":1810.512,
 "going":"Fast",
 "iscomplete":false,
 "meeting":"JEBEL ALI",
 "offtime":"\n «\n 11:45 »\n ",
 "racetype":"FLAT",
 "runners":["885766","773163","902506","800195","880233","306618","778883","772741","724592","818169"],
 "surface":"AW",
 "winningtime":109.14}
